# Setup
title:        Welcome to SMiles GIS
tagline:      QGIS workbook, spatial data, exercises and questions to guide you through the learning process
baseurl:      ""
paginate:     1

# About/contact
author:
  name:       Stephanie Kim Miles
  url:        https://www.linkedin.com/in/stephaniekimmiles/

# Gems
gems:
  - jekyll-paginate

#Others
markdown: kramdown